# Generated by Django 3.2.8 on 2021-10-12 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPTCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'CPT Code',
                'db_table': 'CPTCodes',
            },
        ),
        migrations.CreateModel(
            name='CPTCodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'CPT Code Categories',
                'db_table': 'CPTCodeCategories',
            },
        ),
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ICD10 Codes',
                'db_table': 'ICD10Codes',
            },
        ),
        migrations.CreateModel(
            name='ICD10CodeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ICD10 Code Categories',
                'db_table': 'ICD10CodeCategories',
            },
        ),
        migrations.CreateModel(
            name='ICD10SubCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('sub_code', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_code', to='Core.icd10code')),
            ],
            options={
                'verbose_name_plural': 'ICD10 SubCodes',
                'db_table': 'ICD10SubCodes',
            },
        ),
        migrations.CreateModel(
            name='ICD10CodeSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_category', to='Core.icd10codecategory')),
            ],
            options={
                'verbose_name_plural': 'ICD10 Code Sub Categories',
                'db_table': 'ICD10CodeSubCategories',
            },
        ),
        migrations.AddField(
            model_name='icd10code',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code', to='Core.icd10codesubcategory'),
        ),
        migrations.CreateModel(
            name='CPTCodeSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_category', to='Core.cptcodecategory')),
            ],
            options={
                'verbose_name_plural': 'CPT Code Sub Categories',
                'db_table': 'CPTCodeSubCategories',
            },
        ),
        migrations.CreateModel(
            name='CPTCodesMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_code', models.CharField(max_length=255)),
                ('cpt_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.cptcode')),
            ],
            options={
                'db_table': 'CPTCodesMappings',
            },
        ),
        migrations.AddField(
            model_name='cptcode',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code', to='Core.cptcodesubcategory'),
        ),
    ]
