# Generated by Django 3.2.8 on 2021-10-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20211016_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='cptcode',
            name='local_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CPTCodesMapping',
        ),
    ]
