# Generated by Django 3.2.8 on 2021-10-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_auto_20211016_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cptcode',
            name='local_code',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
