# Generated by Django 3.2.8 on 2021-10-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='query',
            new_name='sql_statement',
        ),
    ]
