# Generated by Django 3.2.8 on 2021-10-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_rename_query_query_sql_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='condition_field',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
