# Generated by Django 3.2.8 on 2021-10-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_query_condition_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='date_format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
