# Generated by Django 3.2.8 on 2021-10-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_query_date_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayloadConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('SVCREC', 'SVCREC'), ('DDC', 'DDC'), ('DDCOUT', 'DDCOUT'), ('REV', 'REV'), ('BEDOCC', 'BEDOCC')], max_length=100)),
                ('chunk_size', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'PayloadConfigs',
                'db_table': 'PayloadConfig',
            },
        ),
    ]
