# Generated by Django 3.2.8 on 2021-10-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_payloadconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payloadconfig',
            options={'verbose_name_plural': 'Payload Configs'},
        ),
    ]
