# Generated by Django 3.2.8 on 2021-11-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_auto_20211106_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='icd10codesubcategory',
            name='identifier',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
