# Generated by Django 3.2.8 on 2021-11-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_icd10codesubcategory_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icd10code',
            name='hdr_local_id',
        ),
        migrations.RemoveField(
            model_name='icd10subcode',
            name='hdr_local_id',
        ),
    ]
