# Generated by Django 3.2.8 on 2021-11-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_auto_20211106_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icd10codecategory',
            old_name='identifier',
            new_name='identifiers',
        ),
        migrations.RenameField(
            model_name='icd10codesubcategory',
            old_name='identifier',
            new_name='identifiers',
        ),
    ]
