# Generated by Django 3.2.8 on 2021-11-08 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_alter_payloadconfig_options'),
        ('Core', '0014_auto_20211106_0752'),
    ]

    operations = [
    ]
